server:
  port: 8080

spring:
  application:
    name: alertas-medicas-bff

  datasource:
    url: jdbc:oracle:thin:@alertasdb_medium
    username: ADMIN
    password: AlertasPass123!
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5

  rabbitmq:
    host: rabbitmq-alertas-medicas
    port: 5672
    username: guest
    password: guest

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
    
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka-alertas-medicas:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: alertas-medicas-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  h2:
    console:
      enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://testazure2026.b2clogin.com/testazure2026.onmicrosoft.com/discovery/v2.0/keys?p=B2C_1_signin

azure:
  b2c:
    tenant-name: ${AZURE_B2C_TENANT_NAME}
    tenant-id: ${AZURE_B2C_TENANT_ID}
    client-id: ${AZURE_B2C_CLIENT_ID}
    client-secret: ${AZURE_B2C_CLIENT_SECRET}
    flow-name: ${AZURE_B2C_FLOW_NAME}

microservicios:
  pacientes:
    url: http://localhost:8081
  alertas:
    url: http://localhost:8082

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

logging:
  level:
    cl.duoc.alertasmedicas: DEBUG
    org.springframework.security: DEBUG