-- ============================================================
-- Sistema de Alertas Médicas – DDL Oracle
-- Ejecutado automáticamente al iniciar el contenedor Oracle
-- ============================================================

-- Tabla de Pacientes
CREATE TABLE pacientes (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR2(100)  NOT NULL,
    apellido        VARCHAR2(100)  NOT NULL,
    fecha_nacimiento DATE          NOT NULL,
    rut             VARCHAR2(12)   NOT NULL UNIQUE,
    habitacion      VARCHAR2(20),
    diagnostico     VARCHAR2(500),
    creado_por      VARCHAR2(200),   -- sub del JWT de quien lo creó
    creado_en       TIMESTAMP DEFAULT SYSTIMESTAMP,
    actualizado_por VARCHAR2(200),
    actualizado_en  TIMESTAMP
);

-- Tabla de Alertas
CREATE TABLE alertas (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id     NUMBER         NOT NULL,
    tipo            VARCHAR2(50)   NOT NULL,  -- FRECUENCIA_CARDIACA, PRESION_ARTERIAL, SpO2, etc.
    valor_medido    NUMBER(8,2)    NOT NULL,
    unidad          VARCHAR2(20)   NOT NULL,  -- bpm, mmHg, %, etc.
    severidad       VARCHAR2(20)   NOT NULL,  -- BAJA, MEDIA, ALTA, CRITICA
    estado          VARCHAR2(20)   DEFAULT 'ACTIVA' NOT NULL,  -- ACTIVA, RESUELTA
    creada_por      VARCHAR2(200),
    creada_en       TIMESTAMP DEFAULT SYSTIMESTAMP,
    resuelta_por    VARCHAR2(200),  -- sub del JWT del médico que la resolvió
    nombre_medico   VARCHAR2(200),  -- nombre del médico (claim "name" del JWT)
    resuelta_en     TIMESTAMP,
    CONSTRAINT fk_alerta_paciente FOREIGN KEY (paciente_id) REFERENCES pacientes(id),
    CONSTRAINT chk_severidad CHECK (severidad IN ('BAJA','MEDIA','ALTA','CRITICA')),
    CONSTRAINT chk_estado    CHECK (estado    IN ('ACTIVA','RESUELTA'))
);

-- Índices para mejorar búsquedas frecuentes
CREATE INDEX idx_alertas_paciente  ON alertas(paciente_id);
CREATE INDEX idx_alertas_estado    ON alertas(estado);
CREATE INDEX idx_alertas_severidad ON alertas(severidad);
CREATE INDEX idx_alertas_creada_en ON alertas(creada_en);

-- Datos de prueba
INSERT INTO pacientes (nombre, apellido, fecha_nacimiento, rut, habitacion, diagnostico)
VALUES ('Juan', 'Pérez', DATE '1965-03-15', '12345678-9', '101-A', 'Insuficiencia cardíaca congestiva');

INSERT INTO pacientes (nombre, apellido, fecha_nacimiento, rut, habitacion, diagnostico)
VALUES ('María', 'González', DATE '1978-11-22', '98765432-1', '203-B', 'Diabetes mellitus tipo 2');

INSERT INTO alertas (paciente_id, tipo, valor_medido, unidad, severidad, estado)
VALUES (1, 'FRECUENCIA_CARDIACA', 145, 'bpm', 'ALTA', 'ACTIVA');

INSERT INTO alertas (paciente_id, tipo, valor_medido, unidad, severidad, estado)
VALUES (1, 'SpO2', 88, '%', 'CRITICA', 'ACTIVA');

COMMIT;
